export const GET_METRICS = 'GET_METRICS';
export const SELECT_METRICS = 'SELECT_METRICS';
export const UNSELECT_METRICS = 'UNSELECT_METRICS';
export const METRIC_API_ERROR_RECEIVED = 'METRIC_API_ERROR_RECEIVED';
export const GET_MULTIPLE_MEASUREMENTS = 'GET_MULTIPLE_MEASUREMENTS';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
